events:
  export:
    timescaledb:
      enabled: false
      min-level: INFO
      host: localhost:5432
      database: qalipsis
      schema: events
      duration-as-nano: false
      linger-period: 10s
      batch-size: 2000
      publishers: 1
      username:
      password:

meters:
  timescaledb:
    enabled: false
    host: localhost
    port: 5432
    database: qalipsis
    schema: meters
    username: qalipsis_user
    password: qalipsis-pwd
    step: PT10S
