events:
  export:
    timescaledb:
      enabled: false
      min-level: INFO
      host: http://localhost:9200
      duration-as-nano: false
      linger-period: 10s
      batch-size: 2000
      publishers: 1
      username:
      password:

# Disables the native micronaut registry.
micronaut.metrics.export.elastic.enabled: false

meters:
  timescaledb:
    host: http://localhost:9200
    enabled: false
    step: PT10S
    index: qalipsis-meters
    index-date-format: yyyy-MM-dd

r2dbc:
  datasources:
    monitoring:
      url: r2dbc:postgresql://localhost:5432/qalipsis
      username: qalipsis
      password: qalipsis
      dialect: POSTGRES
      driverClassName: org.postgresql.Driver

datasources:
  monitoring:
    url: jdbc:postgresql://localhost:5432/qalipsis
    username: qalipsis
    password: qalipsis
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver

liquibase:
  enabled: true
  datasources:
    monitoring:
      change-log: 'classpath:db/liquibase-changelog.xml'
      liquibase-schema: qalipsis_liquibase