events:
  export:
    timescaledb:
      enabled: false
      min-level: INFO
      host: localhost:5432
      database: qalipsis
      schema: qalipsis_ts
      duration-as-nano: false
      linger-period: 10s
      batch-size: 2000
      publishers: 1
      username:
      password:

meters:
  timescaledb:
    enabled: false
    host: localhost
    port: 5432
    database: qalipsis
    schema: qalipsis_ts
    username: qalipsis_user
    password: qalipsis-pwd
    step: PT10S

# Required for the Liquibase script to be able to connect to the DB.
datasources:
  qalipsis_ts:
    url: jdbc:postgresql://localhost:5432/qalipsis
    username: qalipsis
    password: qalipsis
    dialect: POSTGRES
    driverClassName: org.postgresql.Driver
    schema: qalipsis_ts
    schema-generate: none

liquibase:
  enabled: true
  datasources:
    qalipsis_ts:
      change-log: 'classpath:db/liquibase-changelog.xml'
      liquibase-schema: qalipsis_ts