name: Java CI - Main branch

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        java: [ '11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4 # https://github.com/actions/setup-java
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-qalipsis-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-qalipsis-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-wrapper-

      - name: Check licenses
        run: ./gradlew checkLicense
        if: always()

      - name: Tests
        run: ./gradlew check testReport --continue -i --refresh-dependencies

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'
        if: always()
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
          fail_on_failure: true
          summary: true

      - name: Build
        run: ./gradlew build

      - name: Prepare signing configuration
        env:
          SIGNING_KEY_ID: ${{ secrets.SONATYPE_OSS_SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SONATYPE_OSS_SIGNING_PASSWORD }}
          SIGNING_PRIVATE_KEY: ${{ secrets.SONATYPE_OSS_SIGNING_PRIVATE_KEY_BASE_64 }}
        run:
          echo "signing.keyId=$SIGNING_KEY_ID" >> $HOME/.gradle/gradle.properties ;
          echo "signing.password=$SIGNING_PASSWORD" >> $HOME/.gradle/gradle.properties ;
          $SIGNING_PRIVATE_KEY | base64 --decode > /tmp/privateKey.txt ;
          echo "signing.secretKeyRingFile=/tmp/privateKey.txt" >> $HOME/.gradle/gradle.properties

      - name: Prepare publishing configuration
        env:
          OSSRH_USERNAME: ${{secrets.SONATYPE_OSS_USERNAME}}
          OSSRH_PASSWORD: ${{secrets.SONATYPE_OSS_PASSWORD}}
        run:
          echo "ossrhUsername=$OSSRH_USERNAME" >> $HOME/.gradle/gradle.properties ;
          echo "ossrhPassword=$OSSRH_PASSWORD" >> $HOME/.gradle/gradle.properties ;

      - name: Publish artifacts
        run: ./gradlew publish --no-daemon
