name: Java CI - Work in progress

on:
  #  push:
  #    branches-ignore:
  #      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        java: [ '11' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1 # https://github.com/actions/setup-java
        with:
          java-version: ${{ matrix.java }}

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-qalipsis-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-

      - name: Cache Gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-qalipsis-gradle-wrapper-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-qalipsis-gradle-wrapper-

      - name: Tests
        run: ./gradlew check testReport --continue -i --refresh-dependencies

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v2
        if: always()
        with:
          report_paths: '**/build/test-results/*/TEST-*.xml'
          fail_on_failure: true
          summary: true

      - name: Upload Tests results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test Results
          path: ./**/build/test-results/

      - name: Upload Tests report
        uses: actions/upload-artifact@v2
        with:
          name: JUnit Report
          path: ./build/reports/tests/
